# Generated by Django 2.2.6 on 2019-10-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'блюдо', 'verbose_name_plural': 'блюда'},
        ),
    ]
