# Generated by Django 2.2.6 on 2019-11-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20191025_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price_add',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
