# Generated by Django 2.2.6 on 2019-11-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_dish_price_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='price_add',
        ),
    ]
