# Generated by Django 2.2.6 on 2019-11-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191122_1902'),
        ('dishes', '0006_instancedish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstanceDish',
        ),
    ]
