# Generated by Django 2.2.6 on 2019-11-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='355ff15c42e9419fbb021456bc6f8913ad2401366f7d4c958e93466566f1674d', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='6c332200414245a5b66c72f61650ae228a5a4bd634b0403cab3d727095b21d76', max_length=300, null=True),
        ),
    ]
