# Generated by Django 2.2.7 on 2019-11-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191109_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='a55a239ae8c54def8d40f9e134f390c4d1a8f9d31d124d259041e0b0271aaad0', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='8b5b51df7b664c3ebe71625b865fbcd3b6be641ab01d4c43a7f043bd6cacbf6a', max_length=300, null=True),
        ),
    ]
