# Generated by Django 2.2.7 on 2019-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191110_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='e38406e9676246af8e69faa22c65730c4a6f22ed3f0345188ef93f09de88a1a5', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='4cd945bdd87544b3bdda3159cfb4502e9d277ddeb5bc46eaa20005c70141e3ff', max_length=300, null=True),
        ),
    ]
