# Generated by Django 2.2.6 on 2019-11-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191110_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='6b7716766a96418aa302bdc170da9a689038cba9e09f417f92eb1020f7bd3794', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='76d5c275ef9249a18681330e9a6caa995041546213b344e292c186b11a0ce169', max_length=300, null=True),
        ),
    ]
