# Generated by Django 2.2.6 on 2019-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191113_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='f3d8b1e1aace46e781f769438b5ec887024dd8acb4444d2696577e24c0d43507', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='34550e8e1b8d49718ec5cc31793dc995dde0a6f84b554d898d59c8ae01b822fd', max_length=300, null=True),
        ),
    ]
