# Generated by Django 2.2.6 on 2019-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191114_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='f803d52bc4d0470e8008684506f3a4b60a426734216d4315b11f19f3ce8c8d48', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='8b7fe0aeabbb4c26886ebe6b51da2f6b1a755e748d0e4579b0618ab8283e8fbe', max_length=300, null=True),
        ),
    ]
