# Generated by Django 2.2.6 on 2019-11-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191114_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='245aecc3ef0d4348bebfdf992f68b8d72a52285b4de54929a858ac492a3aa2fe', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='385e865b0f904126a8bbdb6652e9aa7c15840b1edb7345ddbd8a2a2ded77d431', max_length=300, null=True),
        ),
    ]
