# Generated by Django 2.2.6 on 2019-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191114_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='0e07c70a6176428a8970692bfe02ba032b427be822d942e5b5ddb1ad5156aeb2', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='e421648c11be41fb8fb3c99ebe1ec85e92028f499e6a40d8929459a443bb94d8', max_length=300, null=True),
        ),
    ]
