# Generated by Django 2.2.6 on 2019-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191118_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='fbbf6ef61dcc4b62a181da4218e2880e6203d2fa119e4cc0b50154c6a4767b47', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='4670673a05d448dc9524c97eec38bf1ac3eb3844e0134f9590b0f5c79a0f64f5', max_length=300, null=True),
        ),
    ]
