# Generated by Django 2.2.6 on 2019-11-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191118_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='0079fdf5490549d2b1034a87399167ec402dff8863624f38bc134e2dee5dd23c', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='0ac9689b8ec14b5caf4c807716bd9156c98b944202334fe4b3dcb4a0ce4e4cdf', max_length=300, null=True),
        ),
    ]
