# Generated by Django 2.2.6 on 2019-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191118_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='75c75ed254df4a32838305cdac4c313ebc0a4afef20342dfb441acd438e11776', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='8a50be5725124d1b9832efdb212a5a1eb343d5aba94e43a29b337bbdbb5f680e', max_length=300, null=True),
        ),
    ]
