# Generated by Django 2.2.6 on 2019-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191118_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='dfdeab10ae91425eb5311d40202ed241e149f8b80be24bc4b7fc0b3064b6e084', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='ebe5ec102f01419fa1e07b3d8265791518f250153e1448e9826a55d54e633b73', max_length=300, null=True),
        ),
    ]
