# Generated by Django 2.2.6 on 2019-11-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191118_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='f8e24da359ea48e494278fe51d7f184dad67641ba6754f3cb56b110a3d2e74c5', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='7b7a3914454e40e493d29bc1d1ced003765cf6958ad64d478bd90525afc1d79a', max_length=300, null=True),
        ),
    ]
