# Generated by Django 2.2.6 on 2019-11-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191118_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='de95280a6d524ce5a8a53a667b5aefa5747900228fdb4c5fa9764547186dc799', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='efff6c7f37e9407fbd2908f94cce472fd88286c4ced54b0ca05308de2a3e072d', max_length=300, null=True),
        ),
    ]
