# Generated by Django 2.2.6 on 2019-11-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20191119_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='54eede4199d848ca9f379fbf87eee5f06e4df93d5e0843ce9cf05ea2fe14dc7f', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='f7066af513374efea83f6a1cd89f10c44d2e4868d5bd41ec9a4604d654bc4c1b', max_length=300, null=True),
        ),
    ]
