# Generated by Django 2.2.6 on 2019-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191119_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='b5082610d449473cb10a903582df4b1a57a28172fbbe4a5db50e9bb3cae0dc86', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='2afbdfb93fca4576a9ea92c7af2ff8368f2d43f121444ad1a6ddaf16603e0c5d', max_length=300, null=True),
        ),
    ]
