# Generated by Django 2.2.6 on 2019-11-19 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191102_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='full_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='order',
            name='place_delivery',
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, to='dishes.InstanceDish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
