# Generated by Django 2.2.6 on 2019-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191119_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, to='dishes.Dish'),
        ),
    ]
